import { Metadata } from "next";
import Header from "../components/header/header";

export const metadata: Metadata = {
    title: "Services Page",
    description: "Generated by create next app",
};


export default function ServiceLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (<div>
        <Header></Header>
        {children}
    </div>);
}
