import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Services Page",
    description: "Generated by create next app",
};


export default function ServiceLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (<div>
        <h1>Header </h1>
        {children}
    </div>);
}
